version: 2
jobs:
  build:
    machine: true
    working_directory: ~/project/capstone
    steps:
      - checkout:
          path: ~/project

      - run:
          name: "Info"
          command: |
            docker-compose --version
            docker version

      - restore_cache:
          key: docker-images-{{ checksum "docker-compose.yml" }}
      - run:
          name: "Build docker images"
          command: |
            mkdir -p docker-cache
            if test -f "docker-cache/capstone.tar"; then
              echo "Loading cached docker images"
              for f in docker-cache/*.tar; do cat $f | docker load; done
              docker load -i docker-cache/built-image.tar
            else
              echo "Building new docker images"
              docker build --cache-from=capstone -t app .
              docker save -o docker-cache/capstone.tar $(docker-compose config | awk '/image: capstone:/ {print $2; exit}')
              docker save -o docker-cache/capstone-postgres.tar $(docker-compose config | awk '/image: capstone-postgres:/ {print $2; exit}')
            fi
            ls -la docker-cache
      - save_cache:
          key: docker-images-{{ checksum "docker-compose.yml" }}
          paths:
            - "docker-cache"

      - run:
          name: "Test"
          command: docker-compose run --rm web fab test

