version: 2.1
jobs:
  build:
    machine: true
    working_directory: ~/project/capstone
    steps:
      - checkout:
          path: ~/project

      - run:
          name: "Info"
          command: |
            docker-compose --version
            docker version

      - restore_cache:
          key: docker-images-{{ checksum "docker-compose.yml" }}
      - run:
          name: "Build docker images"
          command: |
            if test -f ~/docker-cache.tar; then
              echo "Loading cached docker images"
              docker load -i ~/docker-cache.tar
            else
              echo "Building new docker images"
              docker-compose build
              docker save -o ~/docker-cache.tar capstone capstone-postgres
            fi
      - save_cache:
          key: docker-images-{{ checksum "docker-compose.yml" }}
          paths:
            - "~/docker-cache.tar"

      - run:
          name: "Flake8"
          command: docker-compose run web flake8

      - run:
          name: "Test"
          command: |
            mkdir junit
            docker-compose run web pytest \
              -k test_admin_user_authenticate \
              --junitxml=junit/test-results.xml `# write test results so they can be displayed by circleci` \
              --cov --cov-config=setup.cfg     `# write coverage data to .coverage for upload by codecov` \
              --fail-on-template-vars

      - store_test_results:
          path: junit

      - run:
          name: "Upload coverage"
          command: |
            sudo pip install codecov
            codecov
