version: 2.1
jobs:
  build:
    machine: true
    working_directory: ~/project/capstone
    steps:

      # Initial setup
      - checkout:
          path: ~/project
      - run:
          name: "Info"
          command: |
            docker-compose --version
            docker version

      # Quick tests to fail fast on common errors
      - run:
          name: "Flake8"
          command: |
            sudo pip install flake8
            flake8

      # Docker build
      # This whole block shaves a minute or two off of the test runtime by using cached docker images.
      # Otherwise we could omit it entirely and let `docker-compose run` build what it needs to.
      - restore_cache:
          key: docker-images-{{ checksum "docker-compose.yml" }}
      - run:
          name: "Build docker images"
          command: |
            if test -f ~/docker-cache.tar; then
              echo "Loading cached docker images"
              docker load -i ~/docker-cache.tar
            else
              echo "Building new docker images"
              docker-compose build
              docker save -o ~/docker-cache.tar capstone capstone-postgres
            fi
      - save_cache:
          key: docker-images-{{ checksum "docker-compose.yml" }}
          paths:
            - "~/docker-cache.tar"

      # Actual tests
      - run:
          name: "Test"
          command: |
            mkdir -p junit/pytest
            docker-compose run web pytest \
              -k test_admin_user_authenticate \
              --junitxml=junit/pytest/test-results.xml `# write test results so they can be displayed by circleci` \
              --cov --cov-config=setup.cfg     `# write coverage data to .coverage for upload by codecov` \
              --fail-on-template-vars

      # Upload test details to circleci
      - store_test_results:
          path: junit

      # Upload coverage to Codecov
      # Recommended approach is to use an orb: https://circleci.com/blog/making-code-coverage-easy-to-see-with-the-codecov-orb/
      # Currently using python package instead of orb, because of https://github.com/codecov/codecov-circleci-orb/issues/12
      - run:
          name: "Upload coverage"
          command: |
            sudo pip install codecov
            codecov --file .coverage
